import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import {
  transformPageSpeedToAuditReport,
} from "@/lib/audit-transform";
import { runHybridAudit } from "@/lib/audit-service";

export const runtime = "nodejs";

function sanitizeFilename(input: string): string {
  return input.replace(/[^a-zA-Z0-9.-]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

function sectionScore(report: ReturnType<typeof transformPageSpeedToAuditReport>, id: "ux" | "seo" | "ui" | "accessibility"): number {
  return report.sections.find((section) => section.id === id)?.score ?? 0;
}

export async function GET(req: NextRequest) {
  const urlParam = req.nextUrl.searchParams.get("url");
  const strategy = req.nextUrl.searchParams.get("strategy") === "desktop" ? "desktop" : "mobile";
  const expiresRaw = req.nextUrl.searchParams.get("expires");

  if (!urlParam) {
    return NextResponse.json({ error: "Missing url query parameter" }, { status: 400 });
  }

  const expiresAt = expiresRaw ? Number(expiresRaw) : Number.NaN;
  if (!Number.isFinite(expiresAt) || expiresAt <= Date.now()) {
    return NextResponse.json(
      { error: "This download link has expired. Run the audit again to generate a fresh PDF." },
      { status: 410 },
    );
  }

  let normalised = urlParam.trim();
  if (!/^https?:\/\//i.test(normalised)) {
    normalised = `https://${normalised}`;
  }

  try {
    new URL(normalised);
  } catch {
    return NextResponse.json({ error: "Invalid URL" }, { status: 400 });
  }

  let report;
  try {
    const result = await runHybridAudit(normalised, strategy);
    report = transformPageSpeedToAuditReport(result.data, result.normalisedUrl);
  } catch {
    return NextResponse.json(
      {
        error: "Audit data is currently unavailable. Run the audit page again to refresh data.",
      },
      { status: 503 },
    );
  }

  const chunks: Buffer[] = [];
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  doc.fontSize(20).text(report.title);
  doc.moveDown(0.4);
  doc.fontSize(11).fillColor("#475569").text(report.subtitle);

  doc.moveDown(0.8);
  doc.fillColor("#0F172A").fontSize(12).text(`Website: ${report.siteUrl}`);
  doc.text(`Date: ${report.reportDate}`);
  doc.text(`Strategy: ${strategy}`);

  doc.moveDown(0.8);
  doc.fontSize(13).text("Scores");
  doc.fontSize(11);
  doc.text(`Performance: ${sectionScore(report, "ux")}/100`);
  doc.text(`Accessibility: ${sectionScore(report, "accessibility")}/100`);
  doc.text(`SEO: ${sectionScore(report, "seo")}/100`);
  doc.text(`Best Practices: ${sectionScore(report, "ui")}/100`);

  for (const section of report.sections) {
    doc.moveDown(0.9);
    doc.fontSize(13).fillColor("#0F172A").text(`${section.title} (${section.score ?? 0}/100)`);

    if (section.strengths.length > 0) {
      doc.moveDown(0.4);
      doc.fontSize(11).fillColor("#14532d").text("Strengths");
      for (const item of section.strengths.slice(0, 4)) {
        doc.fillColor("#1E293B").text(`- ${item.title}: ${item.body}`);
      }
    }

    if (section.issues.length > 0) {
      doc.moveDown(0.4);
      doc.fontSize(11).fillColor("#9F1239").text("Issues");
      for (const item of section.issues.slice(0, 6)) {
        doc.fillColor("#1E293B").text(`- ${item.title}: ${item.body}`);
      }
    }
  }

  doc.moveDown(1.0);
  doc.fontSize(10).fillColor("#64748B").text(
    "Generated by We Make IT automated audit. This PDF is generated on demand and is not stored permanently.",
  );

  doc.end();

  await new Promise<void>((resolve) => {
    doc.on("end", () => resolve());
  });

  const pdf = Buffer.concat(chunks);
  const filename = `${sanitizeFilename(report.siteName)}-audit-report.pdf`;

  return new NextResponse(pdf, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename=\"${filename}\"`,
      "Cache-Control": "private, max-age=0, s-maxage=0",
    },
  });
}
